displayName: PowerClaw
schemaName: auto_agent_BmTJh
accessControlPolicy: Any
authenticationMode: Integrated
authenticationTrigger: Always
configuration:
  channels:
    - channelId: MsTeams

    - channelId: Microsoft365Copilot

  settings:
    GenerativeActionsEnabled: true

  isAgentConnectable: true
  publishOnImport: true
  gPTSettings:
    defaultSchemaName: auto_agent_BmTJh.gpt.default

  isLightweightBot: false
  aISettings:
    useModelKnowledge: true
    isFileAnalysisEnabled: true
    isSemanticSearchEnabled: true
    optInUseLatestModels: false

  recognizer:
    kind: GenerativeAIRecognizer

  analyticsSettings:
    includeNodeLevelDetailsInTranscript: true

publishedOn: 2026-03-17T17:40:09.0000000Z
template: default-2.1.0
language: 1033